### ISSUE TITLE
Create a sample mkv using ChapterSegmentEditionUID

### ISSUE THREAD

**Issue by mathstuf** [mpv-player/random-stuff#5]
An mkv file should reference another by UID.

**Comment by wm4** [comment]
1 year old issue, not clear if this is a feature request or a reminder to yourself or what this is even useful for. Please reopen if anything moves.

**Comment by mathstuf** [comment]
This was mainly a TODO for myself in order to make such an example to test the MKV chapter code I had written. Never got around to it.
